"""empty message

Revision ID: 01e9fba96bff
Revises: a3030749cebb
Create Date: 2022-09-18 17:44:55.261054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e9fba96bff'
down_revision = 'a3030749cebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'peso',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=False)
    op.add_column('code', sa.Column('email', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'code', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'code', type_='unique')
    op.drop_column('code', 'email')
    op.alter_column('cliente', 'peso',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
