"""empty message

Revision ID: 29c59a4f0c6f
Revises: 7de0dc6c8ff0
Create Date: 2022-08-29 17:52:09.993798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c59a4f0c6f'
down_revision = '7de0dc6c8ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'peso',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=False)
    op.add_column('survey', sa.Column('email', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'survey', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey', type_='unique')
    op.drop_column('survey', 'email')
    op.alter_column('cliente', 'peso',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
