"""empty message

Revision ID: 406a7efed07b
Revises: 2e0cda47b0c8
Create Date: 2022-08-29 11:08:08.697582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406a7efed07b'
down_revision = '2e0cda47b0c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'peso',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey', type_='unique')
    op.drop_column('survey', 'email')
    op.alter_column('cliente', 'peso',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
