"""empty message

Revision ID: 526e35deee90
Revises: a95a9ca30eac
Create Date: 2022-08-31 10:30:48.128413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526e35deee90'
down_revision = 'a95a9ca30eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('fechaPago', sa.DateTime(), nullable=True),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cliente', 'peso',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'peso',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_table('pago')
    # ### end Alembic commands ###
