"""empty message

Revision ID: 793886a9dbc7
Revises: 28af24917ae1
Create Date: 2022-08-24 19:09:16.400063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793886a9dbc7'
down_revision = '28af24917ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('userName', sa.String(length=120), nullable=False),
    sa.Column('lastName', sa.String(length=120), nullable=False),
    sa.Column('dni', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=120), nullable=False),
    sa.Column('objetivo', sa.String(length=120), nullable=False),
    sa.Column('peso', sa.Float(precision=20), nullable=False),
    sa.Column('corrienteDePago', sa.Boolean(), nullable=False),
    sa.Column('fechaDeAlta', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    op.create_table('entreno_contiene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ejercicio', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('repeticiones', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'id_ejercicio')
    )
    op.create_table('ejercicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=False),
    sa.Column('video', sa.String(length=120), nullable=False),
    sa.Column('dificultad', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entreno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('fechaEntreno', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entreno')
    op.drop_table('ejercicio')
    op.drop_table('entreno_contiene')
    op.drop_table('cliente')
    op.drop_table('categoria')
    # ### end Alembic commands ###
