"""empty message

Revision ID: 85065b8c4986
Revises: c66609ee224a
Create Date: 2022-10-20 08:25:54.829611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85065b8c4986'
down_revision = 'c66609ee224a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'peso',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'peso',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
