"""empty message

Revision ID: a9883e3572fd
Revises: 3e6903340589
Create Date: 2022-08-30 07:30:48.277986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9883e3572fd'
down_revision = '3e6903340589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'peso',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=False)
    op.add_column('survey', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'survey', 'cliente', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey', type_='foreignkey')
    op.drop_column('survey', 'cliente_id')
    op.alter_column('cliente', 'peso',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
