"""empty message

Revision ID: ac629fb31ac0
Revises: b724757995d2
Create Date: 2022-08-28 01:28:28.112837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac629fb31ac0'
down_revision = 'b724757995d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective', sa.String(length=120), nullable=False),
    sa.Column('medical', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cliente', 'peso',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'peso',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_table('survey')
    # ### end Alembic commands ###
