"""empty message

Revision ID: c6bfdd1d5fe7
Revises: ac629fb31ac0
Create Date: 2022-08-28 01:45:20.215464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6bfdd1d5fe7'
down_revision = 'ac629fb31ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'peso',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=False)
    op.add_column('survey', sa.Column('dni', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'survey', ['dni'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey', type_='unique')
    op.drop_column('survey', 'dni')
    op.alter_column('cliente', 'peso',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
